package Exercicio_04;

public class Questao4 {
	/*
	 * - Sim, pode ser feito. Não dará erro na compilação
	 * - Não, não faz sentido. Porque o primeiro catch abrange o erro de forma geral,
	 * já o segundo de forma particular. Como o primeiro já vai ser chamado para qualquer
	 * tipo de erro, o segundo se torna inútil. Agora, se as ordem fossem diferente, faria sentido,
	 * porque eu teria um erro particular(no caso Aritimétido), e caso acontecesse um erro diferente
	 * qualquer, o segundo catch seria chamado.
	 */
}
